# Generated by Django 5.0.3 on 2024-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
