# Generated by Django 5.0.3 on 2024-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Events", "0002_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="isClosed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Olay Tarihi"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(null=True, verbose_name="Olay Açıklaması"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.CharField(max_length=50, verbose_name="Olay ikonu"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Olay Adı"),
        ),
    ]
